config/routes.rb
OpenStreetMap::Application.routes.draw do
  use_doorkeeper :scope => "oauth2" do
    controllers :authorizations => "oauth2_authorizations",
                :applications => "oauth2_applications",
                :authorized_applications => "oauth2_authorized_applications"
  end

  use_doorkeeper_openid_connect :scope => "oauth2" if Settings.key?(:doorkeeper_signing_key)

  # API
  namespace :api do
    get "capabilities" => "capabilities#show" # Deprecated, remove when 0.6 support is removed
    get "versions" => "versions#show"
  end

  scope "api/0.6", :module => :api do
    get "capabilities" => "capabilities#show"
    get "permissions" => "permissions#show"

    post "changeset/:id/upload" => "changesets#upload", :as => :changeset_upload, :id => /\d+/
    put "changeset/:id/close" => "changesets#close", :as => :changeset_close, :id => /\d+/
  end

  namespace :api, :path => "api/0.6" do
    resources :changesets, :only => [:index, :create]
    resources :changesets, :path => "changeset", :id => /\d+/, :only => [:show, :update] do
      resource :download, :module => :changesets, :only => :show
      resource :subscription, :controller => :changeset_subscriptions, :only => [:create, :destroy]
      resources :changeset_comments, :path => "comment", :only => :create
    end
    put "changeset/create" => "changesets#create", :as => nil
    post "changeset/:changeset_id/subscribe" => "changeset_subscriptions#create", :changeset_id => /\d+/, :as => nil
    post "changeset/:changeset_id/unsubscribe" => "changeset_subscriptions#destroy", :changeset_id => /\d+/, :as => nil

    resources :changeset_comments, :id => /\d+/, :only => :index do
      resource :visibility, :module => :changeset_comments, :only => [:create, :destroy]
    end
    post "changeset/comment/:changeset_comment_id/unhide" => "changeset_comments/visibilities#create", :changeset_comment_id => /\d+/, :as => nil
    post "changeset/comment/:changeset_comment_id/hide" => "changeset_comments/visibilities#destroy", :changeset_comment_id => /\d+/, :as => nil

    resources :nodes, :only => [:index, :create]
    resources :nodes, :path => "node", :id => /\d+/, :only => [:show, :update, :destroy] do
      scope :module => :nodes do
        resources :ways, :only => :index
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_nodes, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_nodes, :only => :show do
        resource :redaction, :module => :old_nodes, :only => [:create, :destroy]
      end
    end
    put "node/create" => "nodes#create", :as => nil
    post "node/:node_id/:version/redact" => "old_nodes/redactions#create", :node_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :ways, :only => [:index, :create]
    resources :ways, :path => "way", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :ways do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_ways, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_ways, :only => :show do
        resource :redaction, :module => :old_ways, :only => [:create, :destroy]
      end
    end
    put "way/create" => "ways#create", :as => nil
    post "way/:way_id/:version/redact" => "old_ways/redactions#create", :way_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resources :relations, :only => [:index, :create]
    resources :relations, :path => "relation", :id => /\d+/, :only => [:show, :update, :destroy] do
      member do
        get :full, :action => :show, :full => true, :as => nil
      end
      scope :module => :relations do
        resources :relations, :only => :index
      end
      resources :versions, :path => "history", :controller => :old_relations, :only => :index
      resource :version, :path => ":version", :version => /\d+/, :controller => :old_relations, :only => :show do
        resource :redaction, :module => :old_relations, :only => [:create, :destroy]
      end
    end
    put "relation/create" => "relations#create", :as => nil
    post "relation/:relation_id/:version/redact" => "old_relations/redactions#create", :relation_id => /\d+/, :version => /\d+/, :allow_delete => true, :as => nil

    resource :map, :only => :show

    resources :tracepoints, :path => "trackpoints", :only => :index

    resources :users, :only => :index
    resources :users, :path => "user", :id => /\d+/, :only => :show
    resources :user_traces, :path => "user/gpx_files", :module => :users, :controller => :traces, :only => :index
    get "user/details" => "users#details"

    resources :user_preferences, :except => [:new, :create, :edit], :param => :preference_key, :path => "user/preferences" do
      collection do
        put "" => "user_preferences#update_all", :as => ""
      end
    end

    resources :messages, :path => "user/messages", :constraints => { :id => /\d+/ }, :only => [:create, :show, :update, :destroy]
    namespace :messages, :path => "user/messages" do
      resource :inbox, :only => :show
      resource :outbox, :only => :show
    end
    post "/user/messages/:id" => "messages#update", :as => nil

    resources :traces, :path => "gpx", :only => [:create, :show, :update, :destroy], :id => /\d+/ do
      scope :module => :traces do
        resource :data, :only => :show
      end
    end
    post "gpx/create" => "traces#create", :id => /\d+/, :as => :trace_create
    get "gpx/:id/details" => "traces#show", :id => /\d+/, :as => :trace_details

    # Map notes API
    resources :notes, :except => [:new, :edit, :update], :id => /\d+/, :controller => "notes" do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end

      resource :subscription, :only => [:create, :destroy], :controller => "note_subscriptions"
    end

    resources :user_blocks, :only => [:show, :create], :id => /\d+/, :controller => "user_blocks"
    namespace :user_blocks, :path => "user/blocks" do
      resource :active_list, :path => "active", :only => :show
    end
  end

  # Data browsing
  get "/way/:id" => "ways#show", :id => /\d+/, :as => :way
  get "/way/:id/history" => "old_ways#index", :id => /\d+/, :as => :way_history
  resources :old_ways, :path => "/way/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/node/:id" => "nodes#show", :id => /\d+/, :as => :node
  get "/node/:id/history" => "old_nodes#index", :id => /\d+/, :as => :node_history
  resources :old_nodes, :path => "/node/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show
  get "/relation/:id" => "relations#show", :id => /\d+/, :as => :relation
  get "/relation/:id/history" => "old_relations#index", :id => /\d+/, :as => :relation_history
  resources :old_relations, :path => "/relation/:id/history", :id => /\d+/, :version => /\d+/, :param => :version, :only => :show

  resources :changesets, :path => "changeset", :id => /\d+/, :only => :show do
    resource :subscription, :controller => :changeset_subscriptions, :only => [:show, :create, :destroy]
    namespace :changeset_comments, :as => :comments, :path => :comments do
      resource :feed, :only => :show, :defaults => { :format => "rss" }
    end
  end
  get "/changeset/:id/subscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")
  get "/changeset/:id/unsubscribe", :id => /\d+/, :to => redirect(:path => "/changeset/%{id}/subscription")

  resources :notes, :path => "note", :id => /\d+/, :only => [:show, :new]

  get "/user/:display_name/history" => "changesets#index"
  get "/user/:display_name/history/feed" => "changesets#feed", :defaults => { :format => :atom }
  get "/user/:display_name/notes" => "notes#index", :as => :user_notes
  get "/history/friends" => "changesets#index", :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  get "/history/nearby" => "changesets#index", :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  get "/edit" => "site#edit"
  get "/copyright/:copyright_locale" => "site#copyright"
  get "/copyright" => "site#copyright"
  get "/welcome" => "site#welcome"
  get "/fixthemap" => "site#fixthemap"
  get "/help" => "site#help"

app/controllers/api/user_blocks/active_lists_controller.rb
module Api
  module UserBlocks
    class ActiveListsController < ApiController
      before_action -> { authorize(:skip_blocks => true) }

      authorize_resource :class => :active_user_blocks_list

      before_action :set_request_formats

      def show
        @user_blocks = current_user.blocks.active.order(:id => :desc)
        @skip_reason = true
      end
    end
  end
end

app/controllers/api/user_blocks_controller.rb
module Api
  class UserBlocksController < ApiController
    before_action :check_api_writable, :only => :create
    before_action :authorize, :only => :create

    authorize_resource

    before_action :set_request_formats

    def show
      raise OSM::APIBadUserInput, "No id was given" unless params[:id]

      @user_block = UserBlock.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      raise OSM::APINotFoundError
    end

    def create
      raise OSM::APIBadUserInput, "No user was given" unless params[:user]

      user = User.visible.find_by(:id => params[:user])
      raise OSM::APINotFoundError unless user
      raise OSM::APIBadUserInput, "No reason was given" unless params[:reason]
      raise OSM::APIBadUserInput, "No period was given" unless params[:period]

      period = Integer(params[:period], :exception => false)
      raise OSM::APIBadUserInput, "Period should be a number of hours" unless period

      max_period = UserBlock::PERIODS.max
      raise OSM::APIBadUserInput, "Period must be between 0 and #{max_period}" if period.negative? || period > max_period
      raise OSM::APIBadUserInput, "Needs_view must be true if provided" unless params[:needs_view].nil? || params[:needs_view] == "true"

      ends_at = Time.now.utc + period.hours
      needs_view = params[:needs_view] == "true"
      @user_block = UserBlock.create(
        :user => user,
        :creator => current_user,
        :reason => params[:reason],
        :ends_at => ends_at,
        :deactivates_at => (ends_at unless needs_view),
        :needs_view => needs_view
      )
      render :show
    end
  end
end

app/helpers/user_blocks_helper.rb
module UserBlocksHelper
  include ActionView::Helpers::TranslationHelper

  ##
  # returns a translated string representing the status of the
  # user block (i.e: whether it's active, what the expiry time is)
  def block_status(block)
    if block.active?
      # if the block hasn't expired yet show the date, if the user just needs to login show that
      if block.needs_view?
        if block.ends_at > Time.now.utc
          t("user_blocks.helper.time_future_and_until_login_html", :time => friendly_date(block.ends_at))
        else
          t("user_blocks.helper.until_login")
        end
      else
        t("user_blocks.helper.time_future_html", :time => friendly_date(block.ends_at))
      end
    else
      # the max of the last update time or the ends_at time is when this block finished
      # either because the user viewed the block (updated_at) or it expired or was
      # revoked (ends_at)
      last_time = block.deactivates_at || [block.ends_at, block.updated_at].max
      t("user_blocks.helper.time_past_html", :time => friendly_date_ago(last_time))
    end
  end

  def block_short_status(block)
    if block.active?
      if block.ends_at > Time.now.utc
        t("user_blocks.helper.short.active")
      else
        t("user_blocks.helper.short.active_until_read")
      end
    else
      if block.revoker_id.nil?
        if block.deactivates_at > block.ends_at
          t("user_blocks.helper.short.read_html", :time => block_short_time_in_past(block.deactivates_at))
        else
          t("user_blocks.helper.short.ended")
        end
      else
        t("user_blocks.helper.short.revoked_html", :name => link_to(block.revoker.display_name, block.revoker,
                                                                    :class => "username d-inline-block text-truncate text-wrap align-bottom",
                                                                    :dir => "auto"))
      end
    end
  end

  def block_short_time_in_future(time)
    tag.time l(time.to_date),
             :datetime => time.xmlschema,
             :title => t("user_blocks.helper.short.time_in_future_title",
                         :time_absolute => l(time, :format => :friendly),
                         :time_relative => time_ago_in_words(time))
  end

  def block_short_time_in_past(time)
    tag.time l(time.to_date),
             :datetime => time.xmlschema,
             :title => t("user_blocks.helper.short.time_in_past_title",
                         :time_absolute => l(time, :format => :friendly),
                         :time_relative => time_ago_in_words(time, :scope => :"datetime.distance_in_words_ago"))
  end

  def block_duration_in_words(duration)
    # Ensure the requested duration isn't negative, even by a millisecond
    duration = 0 if duration.negative?
    parts = ActiveSupport::Duration.build(duration).parts
    if duration < 1.day
      t("user_blocks.helper.block_duration.hours", :count => parts.fetch(:hours, 0))
    elsif duration < 1.week
      t("user_blocks.helper.block_duration.days", :count => parts[:days])
    elsif duration < 1.month
      t("user_blocks.helper.block_duration.weeks", :count => parts[:weeks])
    elsif duration < 1.year
      t("user_blocks.helper.block_duration.months", :count => parts[:months])
    else
      t("user_blocks.helper.block_duration.years", :count => parts[:years])
    end
  end
end

app/views/user_blocks/_block.html.erb
<tr>
  <% if @show_user_name %>
  <td><%= link_to block.user.display_name, block.user, :class => "username d-inline-block text-truncate text-wrap", :dir => "auto" %></td>
  <% end %>
  <% if @show_creator_name %>
  <td><%= link_to block.creator.display_name, block.creator, :class => "username d-inline-block text-truncate text-wrap", :dir => "auto" %></td>
  <% end %>
  <td><%= h truncate(block.reason) %></td>
  <td><%= block_short_time_in_past(block.created_at) %></td>
  <% if block.ends_at > Time.now.utc %>
  <td><%= block_short_time_in_future(block.ends_at) %></td>
  <% else %>
  <td><%= block_short_time_in_past(block.ends_at) %></td>
  <% end %>
  <td><%= h block_short_status(block) %></td>
  <td><%= link_to t(".show"), block %></td>
  <td><% if can?(:edit, block) %><%= link_to t(".edit"), edit_user_block_path(block) %><% end %></td>
</tr>

app/views/user_blocks/_navigation.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to t(".all_blocks"),
                user_blocks_path,
                :class => ["nav-link", { :active => action_name == "index" }] %>
  </li>
  <% if current_user&.blocks&.exists? %>
    <li class="nav-item">
      <%= link_to t(".blocks_on_me"),
                  user_received_blocks_path(current_user),
                  :class => ["nav-link", { :active => controller_name == "received_blocks" && current_user == @user }] %>
    </li>
  <% end %>
  <% on_user = @user || @user_block&.user %>
  <% if on_user != current_user && on_user&.blocks&.exists? %>
    <li class="nav-item">
      <%= link_to t(".blocks_on_user_html", :user => tag.span(on_user.display_name, :class => "username text-truncate d-inline-block align-bottom", :dir => "auto")),
                  user_received_blocks_path(on_user),
                  :class => ["nav-link", { :active => controller_name == "received_blocks" }] %>
    </li>
  <% end %>
  <% if current_user&.blocks_created&.exists? %>
    <li class="nav-item">
      <%= link_to t(".blocks_by_me"),
                  user_issued_blocks_path(current_user),
                  :class => ["nav-link", { :active => controller_name == "issued_blocks" && current_user == @user }] %>
    </li>
  <% end %>
  <% by_user = @user || @user_block&.creator %>
  <% if by_user != current_user && by_user&.blocks_created&.exists? %>
    <li class="nav-item">
      <%= link_to t(".blocks_by_user_html", :user => tag.span(by_user.display_name, :class => "username text-truncate d-inline-block align-bottom", :dir => "auto")),
                  user_issued_blocks_path(by_user),
                  :class => ["nav-link", { :active => controller_name == "issued_blocks" }] %>
    </li>
  <% end %>
  <% if @user_block&.persisted? %>
    <li class="nav-item">
      <%= link_to t(".block", :id => @user_block.id),
                  user_block_path(@user_block),
                  :class => "nav-link active" %>
    </li>
  <% elsif @user_block&.new_record? %>
    <li class="nav-item">
      <%= link_to t(".new_block"),
                  new_user_block_path,
                  :class => "nav-link active" %>
    </li>
  <% end %>
</ul>

app/views/user_blocks/_page.html.erb
<turbo-frame id="pagination" target="_top" data-turbo="false">
  <table id="block_list" class="table table-borderless table-striped table-sm">
    <thead>
      <tr>
        <% if @show_user_name %>
        <th><%= t ".display_name" %></th>
        <% end %>
        <% if @show_creator_name %>
        <th><%= t ".creator_name" %></th>
        <% end %>
        <th><%= t ".reason" %></th>
        <th><%= t ".start" %></th>
        <th><%= t ".end" %></th>
        <th><%= t ".status" %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <%= render :partial => "user_blocks/block", :collection => @user_blocks %>
  </table>

  <%= render "shared/pagination",
             :translation_scope => "shared.pagination.user_blocks",
             :newer_id => @newer_user_blocks_id,
             :older_id => @older_user_blocks_id %>
</turbo-frame>

app/views/user_blocks/edit.html.erb
<% @title = t ".title", :name => @user_block.user.display_name %>

<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <h1><%= t(".heading_html", :name => link_to(@user_block.user.display_name, @user_block.user)) %></h1>
  <%= render :partial => "navigation" %>
<% end %>

<%= bootstrap_form_for(@user_block) do |f| %>
  <%= f.richtext_field :reason, :cols => 80, :rows => 20, :format => @user_block.reason_format %>

  <% if @user_block.active? && @user_block.creator == current_user %>
    <%= f.form_group do %>
      <%= label_tag "user_block_period", t(".period"), :class => "form-label" %>
      <%= select_tag "user_block_period",
                     options_for_select(UserBlock::PERIODS.collect { |h| [block_duration_in_words(h.hours), h.to_s] },
                                        UserBlock::PERIODS.min_by { |h| (params[:user_block_period].to_i - h).abs }),
                     :class => "form-select" %>
    <% end %>

    <%= f.form_group :needs_view do %>
      <%= f.check_box :needs_view %>
    <% end %>

    <%= f.primary %>
  <% else %>
    <div class="alert alert-info">
      <% if @user_block.active? %>
        <%= t "user_blocks.update.only_creator_can_edit_without_revoking" %>
      <% else %>
        <%= t "user_blocks.update.inactive_block_cannot_be_reactivated" %>
      <% end %>
    </div>

    <%= hidden_field_tag "user_block_period", 0 %>
    <%= hidden_field_tag "user_block[needs_view]", false %>

    <% if @user_block.active? %>
      <%= f.submit t(".revoke"), :class => "btn btn-danger" %>
    <% else %>
      <%= f.primary %>
    <% end %>
  <% end %>
<% end %>

app/views/user_blocks/index.html.erb
<% @title = t(".title") %>

<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <h1><%= t(".heading") %></h1>
  <%= render :partial => "navigation" %>
<% end %>

<% unless @user_blocks.empty? %>
<%= render :partial => "page" %>
<% else %>
<p><%= t ".empty" %></p>
<% end %>

app/views/user_blocks/new.html.erb
<% @title = t ".title", :name => @user.display_name %>

<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <h1><%= t(".heading_html", :name => link_to(@user.display_name, @user)) %></h1>
  <%= render :partial => "navigation" %>
<% end %>

<%= bootstrap_form_for(@user_block) do |f| %>
  <%= hidden_field_tag "display_name", @user.display_name, :autocomplete => "off" %>
  <%= f.richtext_field :reason, :cols => 80, :rows => 20 %>

  <%= f.form_group do %>
    <%= label_tag "user_block_period", t(".period"), :class => "form-label" %>
    <%= select_tag("user_block_period",
                   options_for_select(UserBlock::PERIODS.collect { |h| [block_duration_in_words(h.hours), h.to_s] }, params[:user_block_period]),
                   :class => "form-select") %>
  <% end %>

  <%= f.form_group :needs_view do %>
    <%= f.check_box :needs_view %>
  <% end %>

  <%= f.primary %>
<% end %>

app/views/user_blocks/not_found.html.erb
<p><%= t ".sorry", :id => params[:id] %></p>

<%= link_to t(".back"), user_blocks_path %>

app/views/user_blocks/show.html.erb
<% @title = t(".title",
              :block_on => @user_block.user.display_name,
              :block_by => @user_block.creator.display_name) %>

<% content_for :heading_class, "pb-0" %>
<% content_for :heading do %>
  <h1><%= t(".heading_html",
            :block_on => link_to(@user_block.user.display_name, @user_block.user),
            :block_by => link_to(@user_block.creator.display_name, @user_block.creator)) %></h1>
  <%= render :partial => "navigation" %>
<% end %>

<dl class="row">
  <% if @user_block.revoker %>
    <dt class="col-sm-3"><%= t ".revoker" %></dt>
    <dd class="col-sm-9"><%= link_to @user_block.revoker.display_name, @user_block.revoker %></dd>
  <% end %>

  <dt class="col-sm-3"><%= t ".created" %></dt>
  <dd class="col-sm-9"><%= friendly_date_ago(@user_block.created_at) %></dd>
  <dt class="col-sm-3"><%= t ".duration" %></dt>
  <dd class="col-sm-9"><%= block_duration_in_words(@user_block.ends_at - @user_block.created_at) %></dd>
  <dt class="col-sm-3"><%= t ".status" %></dt>
  <dd class="col-sm-9"><%= block_status(@user_block) %></dd>
  <dt class="col-sm-3"><%= t ".reason" %></dt>
  <dd class="col-sm-9"><div class="richtext text-break"><%= @user_block.reason.to_html %></div></dd>
</dl>

<% if can?(:edit, @user_block) %>
  <div>
    <%= link_to t(".edit"), edit_user_block_path(@user_block), :class => "btn btn-outline-primary" %>
  </div>
<% end %>